/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg17bce7066;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
 /* 1 2 3 4 5
6 7 8 9 10
 
1  4
2  8
3  6
5  9
7  10 */

/**
 *
 * @author User
 */
public class Click_Game extends javax.swing.JFrame {

    /**
     * Creates new form Click_Game
     */
    private int ch=1;
    private int mpair;
    private int mclick; 
    private String p="";
    private Toolkit t;
    public Click_Game() {
        initComponents();
        t=Toolkit.getDefaultToolkit();
        mpair=0;
        mclick=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        img = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        img2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b10.setText("10");
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(img2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1)
                    .addComponent(b2)
                    .addComponent(b3)
                    .addComponent(b4)
                    .addComponent(b5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b6)
                    .addComponent(b7)
                    .addComponent(b8)
                    .addComponent(b9)
                    .addComponent(b10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void check()
    {
        if(mpair==5&&mclick>10)
        {
            JOptionPane.showMessageDialog(null, "You Completed the Game you took "+mclick+" clicks:");
            dispose();
        }
        if(mpair==5&&mclick==10)
        {
            JOptionPane.showMessageDialog(null, "You Won!!");
            dispose();
        }
    }
    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        Image i = t.getImage("F:\\SEM-3\\CSE-2006_Computer_Graphics\\Poster_Assignment\\ubisoft.png").getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        ImageIcon im = new ImageIcon(i);
        if (ch == 1) 
        {
            img2.setIcon(null);
            img.setIcon(im);
        } 
        else 
        {
            img2.setIcon(im);
        }
        ch = ch * -1;
        if(p.equals("b4")==false)
        {
            mclick++;
        }
        else
        {
            mclick++;
            mpair++;
            b1.setEnabled(false);
            b4.setEnabled(false);
            System.out.println("Matched : "+mpair);
            check();
        }
        p="b1";
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        Image i = t.getImage("F:\\SEM-3\\CSE-2006_Computer_Graphics\\Poster_Assignment\\rockstar.png").getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        ImageIcon im = new ImageIcon(i);
        if (ch == 1) 
        {
            img2.setIcon(null);
            img.setIcon(im);
        } 
        else 
        {
            img2.setIcon(im);
        }
        ch = ch * -1;
        if(p.equals("b8")==false)
        {
            mclick++;
        }
        else
        {
            mclick++;
            mpair++;
            b2.setEnabled(false);
            b8.setEnabled(false);
            System.out.println("Matched : "+mpair);
            check();
        }
        p="b2";
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        Image i = t.getImage("F:\\SEM-3\\CSE-2006_Computer_Graphics\\Poster_Assignment\\background.jpg").getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        ImageIcon im = new ImageIcon(i);
        if (ch == 1) 
        {
            img2.setIcon(null);
            img.setIcon(im);
        } 
        else 
        {
            img2.setIcon(im);
        }
        ch = ch * -1;
        if(p.equals("b6")==false)
        {
            mclick++;
        }
        else
        {
            mclick++;
            mpair++;
            b3.setEnabled(false);
            b6.setEnabled(false);
            System.out.println("Matched : "+mpair);
            check();
        }
        p="b3";
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        Image i = t.getImage("F:\\SEM-3\\CSE-2006_Computer_Graphics\\Poster_Assignment\\ubisoft.png").getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        ImageIcon im = new ImageIcon(i);
        if (ch == 1) 
        {
            img2.setIcon(null);
            img.setIcon(im);
        } 
        else 
        {
            img2.setIcon(im);
        }
        ch = ch * -1;
        if(p.equals("b1")==false)
        {
            mclick++;
        }
        else
        {
            mclick++;
            mpair++;
            b1.setEnabled(false);
            b4.setEnabled(false);
            System.out.println("Matched : "+mpair);
            check();
        }
        p="b4";
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        Image i = t.getImage("F:\\SEM-3\\CSE-2006_Computer_Graphics\\Poster_Assignment\\scene.jpg").getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        ImageIcon im = new ImageIcon(i);
        if (ch == 1) 
        {
            img2.setIcon(null);
            img.setIcon(im);
        } 
        else 
        {
            img2.setIcon(im);
        }
        ch = ch * -1;
        if(p.equals("b9")==false)
        {
            mclick++;
        }
        else
        {
            mclick++;
            mpair++;
            b5.setEnabled(false);
            b9.setEnabled(false);
            System.out.println("Matched : "+mpair);
            check();
        }
        p="b5";
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        Image i = t.getImage("F:\\SEM-3\\CSE-2006_Computer_Graphics\\Poster_Assignment\\background.jpg").getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        ImageIcon im = new ImageIcon(i);
        if (ch == 1) 
        {
            img2.setIcon(null);
            img.setIcon(im);
        } 
        else 
        {
            img2.setIcon(im);
        }
        ch = ch * -1;
        if(p.equals("b3")==false)
        {
            mclick++;
        }
        else
        {
            mclick++;
            mpair++;
            b3.setEnabled(false);
            b6.setEnabled(false);
            System.out.println("Matched : "+mpair);
            check();
        }
        p="b6";
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        Image i = t.getImage("F:\\SEM-3\\CSE-2006_Computer_Graphics\\Poster_Assignment\\sunrise.jpg").getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        ImageIcon im = new ImageIcon(i);
        if (ch == 1) 
        {
            img2.setIcon(null);
            img.setIcon(im);
        } 
        else 
        {
            img2.setIcon(im);
        }
        ch = ch * -1;
        if(p.equals("b10")==false)
        {
            mclick++;
        }
        else
        {
            mclick++;
            mpair++;
            b7.setEnabled(false);
            b10.setEnabled(false);
            System.out.println("Matched : "+mpair);
            check();
        }
        p="b7";
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        Image i = t.getImage("F:\\SEM-3\\CSE-2006_Computer_Graphics\\Poster_Assignment\\rockstar.png").getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        ImageIcon im = new ImageIcon(i);
        if (ch == 1) 
        {
            img2.setIcon(null);
            img.setIcon(im);
        } 
        else 
        {
            img2.setIcon(im);
        }
        ch = ch * -1;
        if(p.equals("b2")==false)
        {
            mclick++;
        }
        else
        {
            mclick++;
            mpair++;
            b2.setEnabled(false);
            b8.setEnabled(false);
            System.out.println("Matched : "+mpair);
            check();
        }
        p="b8";
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        Image i = t.getImage("F:\\SEM-3\\CSE-2006_Computer_Graphics\\Poster_Assignment\\scene.jpg").getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        ImageIcon im = new ImageIcon(i);
        if (ch == 1) 
        {
            img2.setIcon(null);
            img.setIcon(im);
        } 
        else 
        {
            img2.setIcon(im);
        }
        ch = ch * -1;
        if(p.equals("b5")==false)
        {
            mclick++;
        }
        else
        {
            mclick++;
            mpair++;
            b5.setEnabled(false);
            b9.setEnabled(false);
            System.out.println("Matched : "+mpair);
            check();
        }
        p="b9";
    }//GEN-LAST:event_b9ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        // TODO add your handling code here:
        Image i = t.getImage("F:\\SEM-3\\CSE-2006_Computer_Graphics\\Poster_Assignment\\sunrise.jpg").getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        ImageIcon im = new ImageIcon(i);
        if (ch == 1) 
        {
            img2.setIcon(null);
            img.setIcon(im);
        } 
        else 
        {
            img2.setIcon(im);
        }
        ch = ch * -1;
        if(p.equals("b7")==false)
        {
            mclick++;
        }
        else
        {
            mclick++;
            mpair++;
            b7.setEnabled(false);
            b10.setEnabled(false);
            System.out.println("Matched : "+mpair);
            check();
        }
        p="b10";
    }//GEN-LAST:event_b10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Click_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Click_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Click_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Click_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Click_Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JLabel img;
    private javax.swing.JLabel img2;
    // End of variables declaration//GEN-END:variables
}
